config/routes.rb
Overniteme::Application.routes.draw do
  devise_for :users
  match "contact" => "static#contact"
  resources :conversations, :only => [:new, :create, :show, :index]
  resources :messages, :only => [:create]
  resources :users, :only => [:index, :show]
  root :to => 'static#home'
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :from, class_name: "User", foreign_key: 'from_id'
  belongs_to :to, class_name: "User", foreign_key: 'to_id'
  has_many :messages
  accepts_nested_attributes_for :messages
  attr_accessible :messages_attributes, :from, :to
  validate :from_can_message_to

  def link_title current_user
    if to == current_user
      "Conversation with #{from.username}"
    else
      "Conversation with #{to.username}"
    end
  end

  private
  def from_can_message_to
    if from.gender == "Male" && to.gender == "Female"
      errors.add(:base, "You cannot create a conversation with this user.")
    end
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :from, class_name: "User", foreign_key: 'from_id'
  belongs_to :conversation
  attr_accessible :from, :to, :subject, :content, :conversation_id
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :gender, :seeking, :description, :profile_picture
  
  validates_format_of :email, with: /^\w+(@columbia\.edu|@barnard\.edu)$/
  
  GENDERS = ['Male','Female']
  SEEKING = ['Men','Women','Either']
  
  validate :gender_is_selected
  validate :seeking_is_selected
  validates :profile_picture, :attachment_presence => true
  validates :username, presence: true, length: { maximum: 20 }
  validates :description, presence: true, length: { maximum: 500 }

  has_attached_file :profile_picture,
    :styles => {
       :small  => "80x80>" 
    },
    :storage => :s3,
    :s3_credentials => "#{Rails.root}/config/s3.yml",
    :path => "/:style/:id/:filename"

  def conversations
    Conversation.where("to_id = ? OR from_id = ?", id, id)
  end
  
  def gender_is_selected
    if !GENDERS.include?(gender)
      errors.add(:gender, "needs to be selected from the dropdown.")
    end
  end
  
  def seeking_is_selected
    if !SEEKING.include?(seeking)
      errors.add(:seeking, "needs to be specified.")
    end
  end
  
  def matches
    if seeking == 'Either'
      return other_users_who_are_seeking('Men') if gender == 'Male'
      return other_users_who_are_seeking('Women') if gender == 'Female'
    elsif gender == 'Male'
      if seeking == 'Women'
        other_users_who_are_seeking('Men').where(gender: 'Female')
      else
        other_users_who_are_seeking('Men').where(gender: 'Male')
      end
    else
      if seeking == 'Men'
        other_users_who_are_seeking('Women').where(gender: 'Male')
      else
        other_users_who_are_seeking('Women').where(gender: 'Female')
      end
    end
  end

  def can_be_messaged_by other_user
    return false if (other_user.gender == 'Male' && gender == 'Female') || self == other_user
    true
  end

  private
  def other_users_who_are_seeking gender
    User.where("seeking = ? OR seeking = ?", 'Either', gender).where("id != ?", self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_filter :authenticate_user!
  def new
    recipient = User.find(params[:user])
    @conversation = Conversation.new(to: recipient)
    @conversation.messages.build
  end

  def create
    @conversation = Conversation.new(params[:conversation])
    @conversation.to = User.find(params[:to_id])
    @conversation.from = current_user
    @conversation.messages.first.from = current_user
    @conversation.save
    redirect_to @conversation
  end

  def show
    @conversation = Conversation.find(params[:id], include: [:messages])
    @message = Message.new
  end

  def index
    @conversations = current_user.conversations.try(:order, "created_at DESC")
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate_user!
  def create
    @message = Message.new(params[:message])
    @message.conversation = Conversation.find(params[:conversation_id])
    @message.save
    redirect_to @message.conversation
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  def index
    @users = current_user.matches.paginate(:page => params[:page], :per_page => 10)
  end
  
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/conversations/_messages_fields.html.erb
<div class="control-group">
  <%= g.label :subject, class: "control-label", for: "conversation_messages_attributes_0_subject" %>
  <div class="controls">
    <%= g.text_field :subject, id: "subject" %>
  </div>
</div>
<div class="control-group">
  <%= g.label :content, class: "control-label", for: "conversation_messages_attributes_0_content" %>
  <div class="controls">
    <%= g.text_area :content, id: "content", rows: "10" %>
  </div>
</div>

app/views/conversations/index.html.erb
<% @conversations.each do |conversation| %>
  <%= link_to conversation.link_title(current_user), conversation %>
  <br><br>
<% end %>

app/views/conversations/new.html.erb
<%= form_for @conversation, :html => { :class => "form-horizontal" } do |f| %>
  <%= hidden_field_tag :to_id, @conversation.to.id %>
  <%= f.fields_for :messages do |builder| %>
    <%= render "messages_fields", :g => builder %>
  <% end %>
  <div class="control-group">
    <div class="controls">
      <%= f.submit "Send", class: "btn" %>
    </div>
  </div>
<% end %>

app/views/conversations/show.html.erb
<section class="row-fluid">
  <h2>
    Conversation between 
    <span id="user_from"><%= link_to @conversation.from.username, @conversation.from, class: "purple" %></span>
    and <span id="user_to"><%= link_to @conversation.to.username, @conversation.to, class: "purple" %></span>
  </h2>
</section>
<br><br>
<% @conversation.messages.each do |message| %>
  <div class="row-fluid">
    <%= message.conversation.from.try(:username) %><br>
    Subject: <%= message.subject %><br>
    <span class="message-content">
      <%= message.content %>
    </span>
  <br><Br>
  </div>
<% end %>
<%= form_for @message do |builder| %>
  <%= hidden_field_tag :conversation_id, @conversation.id %>
  <%= render "messages_fields", g: builder %>
  <div class="control-group">
    <div class="controls">
      <%= builder.submit "Submit", class: "btn" %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Overnite.me</title>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <%= link_to "Overnite.me", root_path, class: "brand" %>
        <div class="nav-collapse">
          <ul class="nav">
            <% if current_user %>
              <li><%= link_to "Matches", users_path %></li>
              <li><%= link_to "Conversations", conversations_path %></li>
            <% end %>
            <li><%= link_to "Contact", contact_path %></li>
            <% if user_signed_in? %>
              <%= link_to user_path(current_user) do %>
                <div class="btn btn-inverse"><i class="icon-pad icon-user icon-white"></i>Profile</div>
              <% end %>
              <%= link_to edit_user_registration_path do %>
                <div class="btn btn-inverse"><i class="icon-pad icon-cog icon-white"></i>Settings</div>
              <% end %>
              <%= link_to destroy_user_session_path, :method => :delete do %>
                <div class="btn btn-primary">Logout</div>
              <% end %>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>
  <br/><br/><br/><br/>
  <div class="container">
    <div class="row-fluid">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>
  </div>
</body>
</html>

app/views/users/index.html.erb
<div class="digg-pagination">
  <%= will_paginate @users, page_links: false %>
</div>
<div class="row-fluid">
  <% if @users.empty? %>
    We're brand new! We don't have any matches for you yet, but check back in a few days.
  <% end %>
  <table class="table">
    <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.profile_picture.url(:small) %></td>
        <td><%= link_to user.username, user %></td>
        <td><%= user.description %></td>
        <td>
          <% if user.can_be_messaged_by current_user %>
            <i class="icon-envelope icon-white"></i>
            <%= link_to "Message #{user.username}", new_conversation_path(user: user) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/users/show.html.erb
<div class="profile-img-main">
  <%= image_tag @user.profile_picture.url %>
</div>
<div class="row-fluid">
  <div class="span5">
    <h1 class="purple"><%= @user.username %></h1>
  </div>
</div>
<br>
<div class="row-fluid">
  <div class="span5">
    <h3 class="orange">
      <%= @user.gender %><br>
      Seeking: <%= @user.seeking %>
    </h3>
  </div>
</div>
<br>
<div class="row-fluid">
  <div class="span5">
    Description:
    <%= @user.description %>
  </div>
</div>
<br><br>
<div class="row-fluid">
  <div class="span5">
    <% if @user.can_be_messaged_by current_user %>
      <i class="icon-envelope icon-white"></i>
      <%= link_to "Message #{@user.username}", new_conversation_path(user: @user) %>
    <% end %>
  </div>
</div>
<br><br><br>